-- Create student_enquiries table
CREATE TABLE IF NOT EXISTS student_enquiries (
    id SERIAL PRIMARY KEY,
    enquiry_id VARCHAR(20) UNIQUE,
    enquiry_date DATE DEFAULT CURRENT_DATE,
    mode_of_enquiry VARCHAR(50),
    student_name VARCHAR(255) NOT NULL,
    gender VARCHAR(20),
    age INT,
    dob DATE,
    mobile_number VARCHAR(20),
    whatsapp_number VARCHAR(20),
    email_id VARCHAR(255),
    perm_address TEXT,
    perm_city VARCHAR(100),
    perm_state VARCHAR(100),
    perm_pin VARCHAR(20),
    curr_address TEXT,
    curr_city VARCHAR(100),
    curr_state VARCHAR(100),
    curr_pin VARCHAR(20),
    highest_qualification VARCHAR(100),
    year_of_passing VARCHAR(50),
    institution_name VARCHAR(255),
    career_objective VARCHAR(100),
    preferred_country VARCHAR(100),
    expected_salary VARCHAR(50),
    willing_to_work_all_india VARCHAR(10),
    work_experience VARCHAR(50),
    company_name VARCHAR(255),
    position VARCHAR(100),
    salary VARCHAR(50),
    location VARCHAR(100),
    skills_trade TEXT,
    father_name VARCHAR(255),
    mother_name VARCHAR(255),
    parent_contact VARCHAR(20),
    parent_occupation VARCHAR(100),
    referred_by VARCHAR(100),
    counsellor_name VARCHAR(255),
    counsellor_code VARCHAR(50),
    will_attend_test VARCHAR(10),
    course_interested VARCHAR(255),
    level_of_course VARCHAR(50),
    training_mode VARCHAR(50),
    batch_timing VARCHAR(50),
    counselling_date DATE,
    counselling_done_by VARCHAR(255),
    interest_level VARCHAR(50),
    follow_up_date DATE,
    remarks TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create student_admissions table (placeholder for now)
CREATE TABLE IF NOT EXISTS student_admissions (
    id SERIAL PRIMARY KEY,
    enquiry_id VARCHAR(20) REFERENCES student_enquiries(enquiry_id),
    student_name VARCHAR(255),
    admission_date DATE DEFAULT CURRENT_DATE,
    status VARCHAR(50) DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
